# reshape 重新赋值不会修改内存地址

In [4]:
import torch
a = torch.arange(12)
b = a.reshape((3,4))
b[:] = 2
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# 一些可能会导致结果分配新内存的操作

In [12]:
X = torch.arange(12).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
print('id(Y):', id(Y))
Y = Y + X
print('id(Y):', id(Y))

id(Y): 4560864016
id(Y): 4737918752


In [14]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 4457997792
id(Z): 4457997792


# torch 中行向量和列向量的理解
torcho 中的行向量是一维的张量，且其转置还是行向量 

列向量是二维度的张量

In [18]:
a = torch.arange(10)
b = torch.arange(10).reshape(10,1)
a, b, a.T

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

# sum 多维操作
sum 操作后会降维，使用 keepdim 可以保持维度不变

一张图通常以三维张量来表示，以 shape[2,3,2] 的三维张量为示例，三个维度分别理解为一张图片的通道数、高、宽

sum(axis=[0,1]) 的理解：先从0维求和，再从1维求和

In [40]:
a = torch.arange(12).reshape(2,3,2)
b = a.sum(axis=[0,1])
print(f'former_dim: {a.shape}', f'later_dim: {b.shape}')
print(a,b,sep='\n')
a = torch.arange(12).reshape(2,3,2)
b = a.sum(axis=[0,1], keepdim=True)
print(f'former_dim: {a.shape}', f'later_dim: {b.shape}')
print(a,b,sep='\n')

former_dim: torch.Size([2, 3, 2]) later_dim: torch.Size([2])
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])
tensor([30, 36])
former_dim: torch.Size([2, 3, 2]) later_dim: torch.Size([1, 1, 2])
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])
tensor([[[30, 36]]])
